[package]
name = "leanig-actix-web"
version = "0.1.0"
edition = "2021"
authors = ["Happy <brunorwanda4@gmail.com.com>"]

[dependencies]
actix-web = "4.9.0"
config = "0.10.1"
dotenv = "0.15.0"
serde = "1.0.214"
